jobs:
  - name: dockercon-1
    type: manifest
    steps:
      - GET: docker-image-1-for
    
  - name: dockercon-2
    type: manifest
    steps:
     - GET: docker-image-2-for
  
  - name: deploy-job-ecs
    type: ecsDeploy
    steps:
      - GET: dockercon-1
      - GET: dockercon-2
      - GET: aws-cluster-res 
  
  
  - name: deploy-job-gke
    type: gkeDeploy
    steps:
      - GET: dockercon-1
      - GET: dockercon-2
      - GET: gke-cluster-res  
      
  - name: deploy-job-dcl
    type: dclDeploy
    steps:
      - GET: dockercon-1
      - GET: dockercon-2
      - GET: dcl-cluster-res        
