jobs:
  - name: dockercon-1-siddarthan
    type: manifest
    steps:
      - GET: docker-image-1-for-siddarthan
    
  - name: dockercon-2-siddarthan
    type: manifest
    steps:
     - GET: docker-image-2-for-siddarthan
  
  - name: deploy-job-ecs-siddarthan
    type: ecsDeploy
    steps:
      - GET: dockercon-1-siddarthan
      - GET: dockercon-2-siddarthan
      - GET: aws-cluster-res 
  
  
  - name: deploy-job-gke-siddarthan
    type: gkeDeploy
    steps:
      - GET: dockercon-1-siddarthan
      - GET: dockercon-2-siddarthan
      - GET: gke-cluster-res-siddarthan
      
  - name: deploy-job-dcl-siddarthan
    type: dclDeploy
    steps:
      - GET: dockercon-1-siddarthan
      - GET: dockercon-2-siddarthan
      - GET: dcl-cluster-res-siddarthan    
