jobs:
  - name: fetch-image-job-for-beta-10000000
    type: manifest
    steps:
      - GET: dockimage-for-double-12
      - GET: dockimage-for-double-13
      - GET: dev-replicas

  - name: fetch-dev-cluster-for-beta-101
    type: gkeDeploy
    steps:
      - GET: fetch-image-job-for-beta-10000000
      - GET: gke-cluster-dev-11
  
 
