jobs:
  - name: fetch-image-job-for-beta-10000000
    type: manifest
    steps:
      - GET: dockimage-for-double-11
      - GET: dev-replicas

  - name: fetch-dev-cluster-for-beta-101
    type: gkeDeploy
    steps:
      - GET: fetch-image-job-for-beta-10000000
      - GET: gke-cluster-dev-11
  
  - name: fetch-prod-cluster-for-beta-1000000
    type: gkeDeploy
    steps:
      - GET: fetch-dev-cluster-for-beta-101
      - GET: gke-cluster-prod-11   
      - GET: prod-replicas


