jobs:
  - name: fetch-image-job-101
    type: manifest
    steps:
      - GET: dockimag
      - GET: dv-opts


  - name: fetch-cluster-job-101
    type: gkeDeploy
    steps:
      - GET: fetch-image-job-101
      - GET: gke-cluster
     

