jobs:
  - name: sidocker-image-1-job
    type: manifest
    steps:
      - GET: sidocker-image-1
    
  - name: sidocker-image-2-job
    type: manifest
    steps:
     - GET: sidocker-image-2
  
  - name: sidocker-dep
    type: ecsDeploy
    steps:
      - GET: sidocker-image-1-job
      - GET: sidocker-image-2-job
      - GET: sidocker-cluster
  
